### PR TITLE
Fixed the extractSetOfValueSetsFromLibrary function in CodeService.js…

### PR DESCRIPTION
**Pull request by sorlioglu**
CQL JSON-ELM standard defines values sets in Libraries to utilize the `valueSets` property, as defined [in the schema](https://cql.hl7.org/elm/schema/library.xsd). 
The [extractSetOfValueSetsFromLibrary in CodeService.js](https://github.com/cqframework/cql-exec-vsac/blob/7da4fffaffedf0ad7da7ade4d9f3a20b4d4c3f35/src/CodeService.js#L231) loops through a library  formatted in JSON-ELM to find all declared value sets. Previously, it looked the the value sets using `library.valuesets`. This is not the proper property to lookup value sets, as defined in the afomentioned schema.

In this pull request, I fixed the `extractSetOfValueSetsFromLibrary` function in [CoderService.js](https://github.com/sorliog/cql-exec-vsac/blob/ea5231aaddaf8e7a9991b619012217918e4e5571/src/CodeService.js#L231)  to extract value sets contained in the `valueSets` property (using `library.valueSets`). Additionally, for backward compatibility, I also use `library.valuesets` property to extract value sets.

### CODE REVIEW

**Review by cmoesel — COMMENTED** [review]
Thank you for finding and fixing this. To be honest, I'm not sure how we've come this far without noticing it. I suspect that _maybe_ when this was originally written, the CQL-to-ELM Translator may have exported ELM using `valuesets`, but I don't think that's been the case for a while...

Our CI found that there is a dependency with a known vulnerability. While it's not directly related to your PR, might you be able to run `npm audit fix` and update this PR so the CI runs clean? If that's too much trouble, let me know and I will accept as-is and follow up with another PR that fixes the vulnerability.

**Comment by sorlioglu** [comment]
@cmoesel Thank you for reviewing my PR.  I ran `npm audit fix` and committed the code in `package-lock.json`. Please rerun the CI workflow.

**Review by cmoesel — CHANGES_REQUESTED** [review]
I apologize. I did not realize before that there is also a prettier code formatting error. To check your code against the lests, linter, and prettier, run:
```
npm run test:plus
```
You can automatically fix prettier violations by running:
```
npm run prettier:fix
```
This is documented at [the bottom of the README](https://github.com/cqframework/cql-exec-vsac?tab=readme-ov-file#testing-the-code).

I apologize for not catching that in my first review.

**Comment by sorlioglu** [comment]
@cmoesel The style checks pass on my machine, and the workflow run on Github was not specific as to what caused the failure. I reran the  `prettier` script and committed the code. Hopefully, that solves it.

**Review by cmoesel — CHANGES_REQUESTED** [review]
I've tried these changes in some existing projects and I'm sorry to report that they introduce problems in some of those projects.

I've investigated and now I understand why it is the way it is. The `library` that is passed in is not intended to be the literal JSON ELM library. It is intended to be an instance of the `Library` class from `cql-execution`. If you [look at the source code](https://github.com/cqframework/cql-execution/blob/master/src/elm/library.ts#L17), that `Library` class has a `valuesets` property (w/ lowercase `s`). So this code is _correct_ to use `valuesets` rather than `valueSets`.

You can construct a `Library` class by passing in the JSON to the constructor (e.g., `new Library(myLibraryElmJson)`) -- and then pass that as the `library` argument in the ensure functions.

BTW -- the errors I ran into when I tried to run it were because `library.valuesets` is sometimes an empty object `({})`, so then `Object.values(library.valuesets)[0]` on line 244 results in `undefined`, causing a dereference error on line 248.

**Comment by sorlioglu** [comment]
@cmoesel Thank you for the clarification. I assume that if the `valuesets` property of the `Library` class was simply renamed to `valueSets`, it would solve the issue of using both a ELM library or the Library class. But that would require all references in all repos that depend on it to be refactored.  
What I don't understand is why reading both `library.valuesets` and `library.valueSets` would introduce problems in other projects. After all, if other project use `library.valuesets`, and my code also reads and processes `library.valuesets`, it should be compatible?

Regarding the dereference errors, I see what the problem is. I can fix it, if you want to go through with the merge.

**Comment by cmoesel** [comment]
@sorliog - I apologize for the long delay. I guess I'm not sure why we should support _both_ the Library class and the ELM. When just the ELM is passed in, the second argument (`extractFromIncluded`) is meaningless since there is no way to traverse included libraries from the ELM alone. Given that `cql-execution` is already a peer dependency, and you can create a library class from ELM pretty easily via `new Library(myELM)` (w/ optional 2nd argument for managing included libraries), it seems better to me if we avoid the confusion of trying to support both. Do you have a use case in which wrapping the ELM in a Library constructor is not feasible?

**Comment by sorlioglu** [comment]
@cmoesel Thank you. I will use `Library` from `cql-execution`.

**Pull request closed without merging**
